#ifndef N1_WINDOW_KEYCODE_H
#define N1_WINDOW_KEYCODE_H

//maps directly to windows VirtualKeycodes VK_



#define KC_LBUTTON                         0x01
#define KC_RBUTTON                         0x02
#define KC_CANCEL                          0x03
#define KC_MBUTTON                         0x04    
#define KC_XBUTTON1                        0x05    
#define KC_XBUTTON2                        0x06    
#define KC_BACK                            0x08
#define KC_TAB                             0x09
#define KC_CLEAR                           0x0C
#define KC_RETURN                          0x0D
#define KC_SHIFT                           0x10
#define KC_CONTROL                         0x11
#define KC_MENU                            0x12
#define KC_PAUSE                           0x13
#define KC_CAPITAL                         0x14
#define KC_KANA                            0x15
#define KC_HANGEUL                         0x15  
#define KC_HANGUL                          0x15
#define KC_JUNJA                           0x17
#define KC_FINAL                           0x18
#define KC_HANJA                           0x19
#define KC_KANJI                           0x19
#define KC_ESCAPE                          0x1B
#define KC_CONVERT                         0x1C
#define KC_NONCONVERT                      0x1D
#define KC_ACCEPT                          0x1E
#define KC_MODECHANGE                      0x1F
#define KC_SPACE                           0x20
#define KC_PRIOR                           0x21
#define KC_NEXT                            0x22
#define KC_END                             0x23
#define KC_HOME                            0x24
#define KC_LEFT                            0x25
#define KC_UP                              0x26
#define KC_RIGHT                           0x27
#define KC_DOWN                            0x28
#define KC_SELECT                          0x29
#define KC_PRINT                           0x2A
#define KC_EXECUTE                         0x2B
#define KC_SNAPSHOT                        0x2C
#define KC_INSERT                          0x2D
#define KC_DELETE                          0x2E
#define KC_HELP                            0x2F
#define KC_LWIN                            0x5B
#define KC_RWIN                            0x5C
#define KC_APPS                            0x5D
#define KC_SLEEP                           0x5F
#define KC_NUMPAD0                         0x60
#define KC_NUMPAD1                         0x61
#define KC_NUMPAD2                         0x62
#define KC_NUMPAD3                         0x63
#define KC_NUMPAD4                         0x64
#define KC_NUMPAD5                         0x65
#define KC_NUMPAD6                         0x66
#define KC_NUMPAD7                         0x67
#define KC_NUMPAD8                         0x68
#define KC_NUMPAD9                         0x69
#define KC_MULTIPLY                        0x6A
#define KC_ADD                             0x6B
#define KC_SEPARATOR                       0x6C
#define KC_SUBTRACT                        0x6D
#define KC_DECIMAL                         0x6E
#define KC_DIVIDE                          0x6F
#define KC_F1                              0x70
#define KC_F2                              0x71
#define KC_F3                              0x72
#define KC_F4                              0x73
#define KC_F5                              0x74
#define KC_F6                              0x75
#define KC_F7                              0x76
#define KC_F8                              0x77
#define KC_F9                              0x78
#define KC_F10                             0x79
#define KC_F11                             0x7A
#define KC_F12                             0x7B
#define KC_F13                             0x7C
#define KC_F14                             0x7D
#define KC_F15                             0x7E
#define KC_F16                             0x7F
#define KC_F17                             0x80
#define KC_F18                             0x81
#define KC_F19                             0x82
#define KC_F20                             0x83
#define KC_F21                             0x84
#define KC_F22                             0x85
#define KC_F23                             0x86
#define KC_F24                             0x87
#define KC_NAVIGATION_VIEW                 0x88
#define KC_NAVIGATION_MENU                 0x89
#define KC_NAVIGATION_UP                   0x8A
#define KC_NAVIGATION_DOWN                 0x8B
#define KC_NAVIGATION_LEFT                 0x8C
#define KC_NAVIGATION_RIGHT                0x8D
#define KC_NAVIGATION_ACCEPT               0x8E
#define KC_NAVIGATION_CANCEL               0x8F
#define KC_NUMLOCK                         0x90
#define KC_SCROLL                          0x91
#define KC_OEM_NEC_EQUAL                   0x92   
#define KC_OEM_FJ_JISHO                    0x92   
#define KC_OEM_FJ_MASSHOU                  0x93   
#define KC_OEM_FJ_TOUROKU                  0x94   
#define KC_OEM_FJ_LOYA                     0x95   
#define KC_OEM_FJ_ROYA                     0x96   
#define KC_LSHIFT                          0xA0
#define KC_RSHIFT                          0xA1
#define KC_LCONTROL                        0xA2
#define KC_RCONTROL                        0xA3
#define KC_LMENU                           0xA4
#define KC_RMENU                           0xA5
#define KC_BROWSER_BACK                    0xA6
#define KC_BROWSER_FORWARD                 0xA7
#define KC_BROWSER_REFRESH                 0xA8
#define KC_BROWSER_STOP                    0xA9
#define KC_BROWSER_SEARCH                  0xAA
#define KC_BROWSER_FAVORITES               0xAB
#define KC_BROWSER_HOME                    0xAC
#define KC_VOLUME_MUTE                     0xAD
#define KC_VOLUME_DOWN                     0xAE
#define KC_VOLUME_UP                       0xAF
#define KC_MEDIA_NEXT_TRACK                0xB0
#define KC_MEDIA_PREV_TRACK                0xB1
#define KC_MEDIA_STOP                      0xB2
#define KC_MEDIA_PLAY_PAUSE                0xB3
#define KC_LAUNCH_MAIL                     0xB4
#define KC_LAUNCH_MEDIA_SELECT             0xB5
#define KC_LAUNCH_APP1                     0xB6
#define KC_LAUNCH_APP2                     0xB7
#define KC_OEM_1                           0xBA
#define KC_OEM_PLUS                        0xBB
#define KC_OEM_COMMA                       0xBC
#define KC_OEM_MINUS                       0xBD
#define KC_OEM_PERIOD                      0xBE
#define KC_OEM_2                           0xBF
#define KC_OEM_3                           0xC0
#define KC_GAMEPAD_A                       0xC3
#define KC_GAMEPAD_B                       0xC4
#define KC_GAMEPAD_X                       0xC5
#define KC_GAMEPAD_Y                       0xC6
#define KC_GAMEPAD_RIGHT_SHOULDER          0xC7
#define KC_GAMEPAD_LEFT_SHOULDER           0xC8
#define KC_GAMEPAD_LEFT_TRIGGER            0xC9
#define KC_GAMEPAD_RIGHT_TRIGGER           0xCA
#define KC_GAMEPAD_DPAD_UP                 0xCB
#define KC_GAMEPAD_DPAD_DOWN               0xCC
#define KC_GAMEPAD_DPAD_LEFT               0xCD
#define KC_GAMEPAD_DPAD_RIGHT              0xCE
#define KC_GAMEPAD_MENU                    0xCF
#define KC_GAMEPAD_VIEW                    0xD0
#define KC_GAMEPAD_LEFT_THUMBSTICK_BUTTON  0xD1
#define KC_GAMEPAD_RIGHT_THUMBSTICK_BUTTON 0xD2
#define KC_GAMEPAD_LEFT_THUMBSTICK_UP      0xD3
#define KC_GAMEPAD_LEFT_THUMBSTICK_DOWN    0xD4
#define KC_GAMEPAD_LEFT_THUMBSTICK_RIGHT   0xD5
#define KC_GAMEPAD_LEFT_THUMBSTICK_LEFT    0xD6
#define KC_GAMEPAD_RIGHT_THUMBSTICK_UP     0xD7
#define KC_GAMEPAD_RIGHT_THUMBSTICK_DOWN   0xD8
#define KC_GAMEPAD_RIGHT_THUMBSTICK_RIGHT  0xD9
#define KC_GAMEPAD_RIGHT_THUMBSTICK_LEFT   0xDA
#define KC_OEM_4                           0xDB
#define KC_OEM_5                           0xDC
#define KC_OEM_6                           0xDD
#define KC_OEM_7                           0xDE
#define KC_OEM_8                           0xDF
#define KC_OEM_AX                          0xE1
#define KC_OEM_102                         0xE2
#define KC_ICO_HELP                        0xE3
#define KC_ICO_00                          0xE4
#define KC_PROCESSKEY                      0xE5
#define KC_ICO_CLEAR                       0xE6
#define KC_PACKET                          0xE7
#define KC_OEM_RESET                       0xE9
#define KC_OEM_JUMP                        0xEA
#define KC_OEM_PA1                         0xEB
#define KC_OEM_PA2                         0xEC
#define KC_OEM_PA3                         0xED
#define KC_OEM_WSCTRL                      0xEE
#define KC_OEM_CUSEL                       0xEF
#define KC_OEM_ATTN                        0xF0
#define KC_OEM_FINISH                      0xF1
#define KC_OEM_COPY                        0xF2
#define KC_OEM_AUTO                        0xF3
#define KC_OEM_ENLW                        0xF4
#define KC_OEM_BACKTAB                     0xF5
#define KC_ATTN                            0xF6
#define KC_CRSEL                           0xF7
#define KC_EXSEL                           0xF8
#define KC_EREOF                           0xF9
#define KC_PLAY                            0xFA
#define KC_ZOOM                            0xFB
#define KC_NONAME                          0xFC
#define KC_PA1                             0xFD
#define KC_OEM_CLEAR                       0xFE

#endif
